In [1]:
import pandas as pd
datos = pd.read_csv('./Iris.csv')
print(datos.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target
for i in range(5):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7)
    # print(x_train.shape, x_test.shape)
    print(y_test)


[0 0 2 0 2 1 1 2 0 1 1 0 2 0 2 1 2 2 1 0 2 0 1 1 2 0 0 1 1 0 0 0 0 2 1 1 0
 0 0 2 1 1 2 2 2 1 1 2 1 2 1 1 2 2 2 0 1 2 2 1 1 1 1 2 2 0 0 1 1 2 0 1 2 1
 0 0 0 2 0 1 0 1 1 0 2 0 1 1 2 0 0 2 2 2 0 0 0 0 1 0 2 1 2 0 0]
[1 1 1 2 0 1 0 2 1 2 0 0 0 1 0 1 2 2 1 2 1 1 0 2 2 0 0 0 0 0 0 0 2 0 1 0 1
 1 1 1 2 1 0 0 1 1 0 0 1 2 0 2 2 1 1 0 2 2 2 2 2 0 1 1 0 1 1 0 0 0 1 1 1 1
 1 1 2 2 2 1 2 0 0 1 1 2 2 2 0 1 0 1 2 2 2 0 2 2 2 1 2 1 2 0 0]
[0 1 0 1 2 0 2 1 1 2 1 0 0 2 0 0 1 0 1 2 2 2 0 2 2 2 1 2 1 1 0 1 2 2 2 1 0
 2 2 0 2 0 2 0 2 2 1 1 0 0 1 2 0 0 2 1 2 2 0 2 0 1 1 1 1 1 2 1 2 0 0 1 1 2
 1 2 0 2 0 1 2 1 1 2 0 0 0 1 0 1 2 2 2 1 0 1 1 0 1 1 0 2 0 2 0]
[0 2 1 2 1 0 2 0 1 2 0 0 2 0 0 0 2 0 1 1 1 2 1 2 0 0 0 2 2 1 1 2 2 0 1 0 1
 2 1 1 1 2 0 0 1 0 0 2 2 1 0 2 0 1 2 2 2 1 2 2 0 2 2 2 0 1 0 2 2 1 1 2 2 1
 1 0 0 0 1 0 0 2 0 0 2 2 0 1 2 2 1 0 2 2 1 0 1 0 0 2 1 2 1 2 2]
[2 2 2 2 2 2 1 2 2 1 0 0 0 0 1 0 2 1 0 0 1 1 1 2 1 0 2 0 1 2 1 0 2 2 2 0 2
 2 0 1 2 0 1 2 1 0 1 0 1 2 0 2 0 1 0 2 0 0 0 2 2 2 2 1 2 2 2 2 1 0 0 

In [11]:
from sklearn.tree import DecisionTreeClassifier
clasificador = DecisionTreeClassifier(random_state=42)
clasificador.fit(x_train, y_train)
# Prueba General por el usuario
print(clasificador.predict([[5.4,3.4,1.7,0.2], [5.1, 3.7, 1.5, 0.4]]))
# Consulta con los datos de testeo
print(clasificador.predict(x_test))
print(y_test)

[0 0]
[2 1 2 2 1 2 1 2 2 1 0 0 0 0 1 0 2 1 0 0 1 1 1 2 1 0 2 0 1 2 1 0 2 2 2 0 1
 2 0 1 2 0 1 2 2 0 1 0 1 2 0 2 0 1 0 2 0 0 0 2 2 2 1 1 2 1 2 2 1 0 0 0 0 1
 1 0 2 1 1 2 0 1 0 1 1 2 1 1 1 0 2 2 0 1 0 1 0 0 0 0 0 1 1 1 1]
[2 2 2 2 2 2 1 2 2 1 0 0 0 0 1 0 2 1 0 0 1 1 1 2 1 0 2 0 1 2 1 0 2 2 2 0 2
 2 0 1 2 0 1 2 1 0 1 0 1 2 0 2 0 1 0 2 0 0 0 2 2 2 2 1 2 2 2 2 1 0 0 0 0 1
 1 0 2 1 2 2 0 1 0 1 1 2 1 1 1 0 2 2 0 1 0 1 0 0 0 0 0 1 2 1 2]


In [12]:
from sklearn.metrics import confusion_matrix
y_response = clasificador.predict(x_test)
print(confusion_matrix(y_test, y_response))

[[36  0  0]
 [ 0 30  1]
 [ 0  8 30]]


In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_response))

0.9142857142857143


In [17]:
import numpy as np
from sklearn.preprocessing import Normalizer

preprocesamiento = Normalizer()
x = preprocesamiento.fit_transform(x)
acuary = []
for i in range(100):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7)
    clasificador = DecisionTreeClassifier(random_state=42)
    clasificador.fit(x_train, y_train)
    y_response = clasificador.predict(x_test)
    acuary.append(accuracy_score(y_test, y_response))
print(acuary)
print(np.mean(acuary))

[0.8952380952380953, 0.9238095238095239, 0.9238095238095239, 0.8952380952380953, 0.8857142857142857, 0.780952380952381, 0.9809523809523809, 0.9809523809523809, 0.9238095238095239, 0.9428571428571428, 0.8761904761904762, 0.9904761904761905, 0.9047619047619048, 0.9333333333333333, 0.9047619047619048, 0.9047619047619048, 0.9238095238095239, 0.8380952380952381, 0.8380952380952381, 0.8952380952380953, 0.8952380952380953, 0.9238095238095239, 0.9523809523809523, 0.8285714285714286, 0.9523809523809523, 0.8285714285714286, 0.9142857142857143, 0.8857142857142857, 0.9714285714285714, 0.9523809523809523, 0.9142857142857143, 0.9333333333333333, 0.8952380952380953, 0.9047619047619048, 0.8476190476190476, 0.8857142857142857, 0.9619047619047619, 0.9047619047619048, 0.8476190476190476, 0.8666666666666667, 0.9238095238095239, 0.9047619047619048, 0.9809523809523809, 0.9428571428571428, 0.9142857142857143, 0.8857142857142857, 0.9809523809523809, 0.9047619047619048, 0.9333333333333333, 0.8571428571428571, 

In [28]:
from sklearn.impute import SimpleImputer
import pandas as pd
datos2 = pd.read_csv('./datos.csv')

# print(datos2["genero"])
# print(datos2["edad"])

columnasnum = datos2.select_dtypes(include=['number']).columns
columnascad = datos2.select_dtypes(include=['object']).columns
print(columnasnum)
print(columnasnum)

def completa_media(df): 
    columnas = datos2.select_dtypes(include=['number']).columns
    for col in columnas:
        media = df[col].mean()
        df[col].fillna(media, inplace=True)
    return df

def completa_moda(df): 
    columnas = datos2.select_dtypes(include=['object']).columns
    for col in columnas:
        moda = df[col].mode()[0]
        df[col].fillna(moda, inplace=True)
    return df
print("------------------- Completando con la media -------------------")
datos3 = completa_media(datos2)
print(datos3)
print("------------------- Completando con la moda -------------------")
datos4 = completa_moda(datos3)
print(datos4)


Index(['edad'], dtype='object')
Index(['edad'], dtype='object')
------------------- Completando con la media -------------------
    edad genero   cabello
0     25      f     corto
1     30      m     largo
2     22     nb  ondulado
3     28      f    teñido
4     35      m    rapado
5     40     nb     calvo
6     27      f  ondulado
7     32      m    teñido
8     24     nb    rapado
9     29      f     calvo
10    31      m  ondulado
11    26     nb    teñido
12    33      f    rapado
13    23      m     calvo
------------------- Completando con la moda -------------------
    edad genero   cabello
0     25      f     corto
1     30      m     largo
2     22     nb  ondulado
3     28      f    teñido
4     35      m    rapado
5     40     nb     calvo
6     27      f  ondulado
7     32      m    teñido
8     24     nb    rapado
9     29      f     calvo
10    31      m  ondulado
11    26     nb    teñido
12    33      f    rapado
13    23      m     calvo


/tmp/ipykernel_2844/406385528.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(media, inplace=True)
/tmp/ipykernel_2844/406385528.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.met